---
amqphub:
  amqp10jms:
    remote-url: "amqp://127.0.0.1:5672"
cxf:
  path: /rest
deployment:
  kjars:
    - alias: evaluation-business-application-kjar
      artifactId: evaluation
      containerId: evaluation-1.0-SNAPSHOT
      groupId: com.sgitario.kjar-examples
      version: 1.0-SNAPSHOT
    - alias: evaluation-business-application-kjar
      artifactId: evaluation
      containerId: evaluation-2.0-SNAPSHOT
      groupId: com.sgitario.kjar-examples
      version: 2.0-SNAPSHOT
jbpm:
  executor:
    enabled: false
    ##    retries: 5
    ##    interval: 0
    ##    threadPoolSize: 1
    ##    timeUnit: SECONDS
kieserver:
  auditQueueName: bpmqueue
  casemgmt:
    enabled: true
  dmn:
    enabled: true
  drools:
    enabled: true
  jbpm:
    enabled: true
  jbpmui:
    enabled: true
  location: "http://${server.address}:${server.port}${cxf.path}/server"
  optaplanner:
    enabled: true
  serverId: business-application-service
  serverName: business-application-service
  swagger:
    enabled: true
logging:
  level:
    com:
      arjuna:
        ats: INFO
    org:
      kie:
        server:
          common: ERROR
    root: INFO
narayana:
  dbcp:
    enabled: true
    maxTotal: 20
server:
  address: "0.0.0.0"
  port: 8090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE"
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create-drop
        show_sql: true
  jta:
    narayana:
      transaction-manager-id: 1
workflow:
  service:
    account:
      password: "${workflow_service_account_pass:kieserver}"
      username: "${workflow_service_account_user:kieserver}"
  url: "${workflow_url:http://localhost:}"
